detectors:
  DuplicateMethodCall:
    exclude:
      - Kamerling::RepoBehaviour
    max_calls: 2

  IrresponsibleModule:
    enabled: false

  NestedIterators:
    max_allowed_nesting: 2

  TooManyStatements:
    exclude:
      - Kamerling::RepoBehaviour
