AllCops:
  Exclude:
    - tmp/**/*

Layout/ExtraSpacing:
  Enabled: false

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Metrics/AbcSize:
  Exclude:
    - test/kamerling/*_behaviour.rb

Metrics/BlockLength:
  Exclude:
    - kamerling.gemspec
    - lib/kamerling/migrations/**/*.rb
    - test/**/*.rb

Metrics/MethodLength:
  Exclude:
    - test/kamerling/*_behaviour.rb

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
