AllCops:
  Exclude:
    - tmp/**/*

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SingleSpaceBeforeFirstArg:
  Enabled: false

Style/TrailingComma:
  EnforcedStyleForMultiline: comma
