AllCops:
  Exclude:
    - tmp/**/*

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ExtraSpacing:
  Enabled: false

Style/SingleSpaceBeforeFirstArg:
  Exclude:
    - lib/kamerling/migrations/**/*

Style/TrailingComma:
  EnforcedStyleForMultiline: comma
