AccessModifierIndentation:
  Enabled: false

AlignArray:
  Enabled: false

AlignHash:
  Enabled: false

AlignParameters:
  Enabled: false

AndOr:
  Enabled: false

CaseEquality:
  Enabled: false

ConstantName:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

Documentation:
  Enabled: false

EndAlignment:
  Enabled: false

HandleExceptions:
  Enabled: false

IndentationWidth:
  Enabled: false

MethodDefParentheses:
  Enabled: false

MethodName:
  Enabled: false

SignalException:
  Enabled: false

SpaceAroundOperators:
  Enabled: false

TrailingComma:
  Enabled: false
