AllCops:
  Exclude:
    - tmp/**/*
  TargetRubyVersion: 2.3

Layout/ExtraSpacing:
  Enabled: false

Layout/SpaceBeforeFirstArg:
  Exclude:
    - lib/kamerling/migrations/**/*

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Metrics/AbcSize:
  Exclude:
    - test/kamerling/*_behaviour.rb

Metrics/BlockLength:
  Exclude:
    - kamerling.gemspec
    - lib/kamerling/migrations/**/*.rb
    - test/**/*.rb

Metrics/MethodLength:
  Exclude:
    - test/kamerling/*_behaviour.rb

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
