AccessControl:
  Enabled: false

AlignArray:
  Enabled: false

AlignHash:
  Enabled: false

CaseEquality:
  Enabled: false

ConstantName:
  Enabled: false

DefWithoutParentheses:
  Enabled: false

Documentation:
  Enabled: false

EndAlignment:
  Enabled: false

IndentationWidth:
  Enabled: false

MethodLength:
  Enabled: false

MethodName:
  Enabled: false

SignalException:
  Enabled: false

SpaceAroundOperators:
  Enabled: false
