AccessModifierIndentation:
  Enabled: false

AndOr:
  Enabled: false

Documentation:
  Enabled: false

EndAlignment:
  Enabled: false

HandleExceptions:
  Exclude:
    - lib/kamerling/server/tcp.rb
    - lib/kamerling/server/udp.rb

IndentationWidth:
  Enabled: false

MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

SingleSpaceBeforeFirstArg:
  Enabled: false

TrailingComma:
  EnforcedStyleForMultiline: comma
