AllCops:
  Exclude:
    - tmp/**/*

Metrics/AbcSize:
  Exclude:
    - test/kamerling/*_behaviour.rb

Metrics/MethodLength:
  Exclude:
    - test/kamerling/*_behaviour.rb

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ExtraSpacing:
  Enabled: false

Style/SingleSpaceBeforeFirstArg:
  Exclude:
    - lib/kamerling/migrations/**/*

Style/TrailingComma:
  EnforcedStyleForMultiline: comma
