inherit_from: rubocop-todo.yml

AccessModifierIndentation:
  Enabled: false

AndOr:
  Enabled: false

Documentation:
  Enabled: false

EndAlignment:
  Enabled: false

HandleExceptions:
  Exclude:
    - lib/kamerling/server/sock.rb

IndentationWidth:
  Enabled: false

MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

TrailingComma:
  EnforcedStyleForMultiline: comma
