DuplicateMethodCall:
  exclude:
    - Kamerling::Handler#handle
    - Kamerling::Handler#process
    - Kamerling::Logging#log_dispatcher
    - Kamerling::Logging#log_server
    - Kamerling::Mapper#self.to_h

IrresponsibleModule:
  enabled: false

NestedIterators:
  max_allowed_nesting: 2

UnusedParameters:
  exclude:
    - Kamerling::Server::HTTP#initialize
