DuplicateMethodCall:
  exclude:
  - Kamerling#self.class_definition_from
  - Kamerling::Handler#handle

IrresponsibleModule:
  enabled: false

NestedIterators:
  max_allowed_nesting: 2

UnusedParameters:
  exclude:
  - Kamerling::Server::HTTP#initialize
