DuplicateMethodCall:
  exclude:
    - Kamerling::Handler#handle
    - Kamerling::Handler#process
    - Kamerling::Logging#log_dispatcher
    - Kamerling::Logging#log_server
    - Kamerling::Mapper#self.to_h

FeatureEnvy:
  exclude:
    # https://github.com/troessner/reek/issues/53
    - Kamerling::NetDispatcher
    - Kamerling::UUID

IrresponsibleModule:
  enabled: false

NestedIterators:
  max_allowed_nesting: 2

UnusedParameters:
  exclude:
    - Kamerling::Server::HTTP#initialize

UtilityFunction:
  exclude:
    # https://github.com/troessner/reek/issues/27
    - Kamerling::NetDispatcher
    - Kamerling::UUID
